test mods. update vednn-def.h

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -24,11 +24,6 @@ vars:
 	echo 'LIBVEDNN          $(LIBVEDNN)'
 	echo 'MAKECMDGOALS      $(MAKECMDGOALS)'
 	echo 'first             $(word 1,$(MAKECMDGOALS))'
-demo: all
-	{ ./vednn_conv_test -H 8e8 -p params/conv/alexnet.txt -T ConvForward; ftrace; \
-		./vednn_linear_test -H 0.8e9 -p params/linear/alexnet.txt -T LinearForward; ftrace; \
-		./vednn_pool_test   -H 0.8e9 -p params/pool/alexnet.txt   -T MaxPoolForward; ftrace; \
-		} 2>&1 | tee mk-test.log
 
 SRCS	= vednn_conv_test.c vednn_linear_test.c vednn_pool_test.c vednn_helper.c convolution_gemm.c linear_gemm.c maxpooling.c
 OBJS	= $(SRCS:%.c=%.o)
@@ -46,6 +41,7 @@ CFLAGS	+= -I${VEDNN_DIR}/include
 LDLIBS	+= -L${VEDNN_DIR}/lib -l${LIBVEDNN}
 
 ifeq ($(OPENMP),YES)
+CFLAGS	+= -fopenmp
 LDLIBS  += -L$(BLAS_LIB_DIR) -lblas_openmp
 LDLIBS  += -fopenmp
 else
@@ -53,14 +49,35 @@ LDLIBS	+= -L$(BLAS_LIB_DIR) -lblas_sequential
 endif
 
 ifeq ($(FTRACE),YES)
-CFLAGS		+= -DFTRACE
+CFLAGS		+= -ftrace -pthread -DFTRACE
 LDLIBS		+= -ftrace
+ifeq ($(OPENMP),YES)
+LDFLAGS		+= -pthread # ncc-2.x.x recommends
+endif
 endif
 
 vednn_conv_test : vednn_conv_test.o vednn_helper.o convolution_gemm.o
 vednn_linear_test : vednn_linear_test.o vednn_helper.o linear_gemm.o
 vednn_pool_test : vednn_pool_test.o vednn_helper.o maxpooling.o
-
+test.log : vednn_conv_test vednn_linear_test vednn_pool_test Makefile
+	{ ./vednn_conv_test -H 0.8e9 -p params/conv/alexnet.txt   -T ConvForward    \
+		|| echo "Error: vednn_conv_test"; ftrace || true; \
+	./vednn_linear_test -H 0.8e9 -p params/linear/alexnet.txt -T LinearForward  \
+		|| echo "Error: vednn_linear_test"; ftrace || true; \
+	./vednn_pool_test   -H 0.8e9 -p params/pool/alexnet.txt   -T MaxPoolForward \
+		|| echo "Error: vednn_pool_test"; ftrace || true; \
+	} >& $@
+#convolution_gemm-clang.s: convolution_gemm.c
+#	$(CLANG) $(CLANG_FLAGS) -o $@ -S $<
+convolution_gemm-ncc.s: convolution_gemm.c
+	$(CC) $(CFLAGS) -std=gnu11 -report-all -Wall \
+		-O3 -fcse-after-vectorization -msched-block \
+		-o $@ -S $<
+convolution_gemm.o: convolution_gemm-ncc.s
+	$(CC) $(CFLAGS) -o $@ -c $<
+.PHONY: force
+jitconv resnext-t8.log: force
+	$(MAKE) -fMakefile.big $@
 clean:
 	rm -f $(OBJS) $(TARGETS) *.L *.O *.s ftrace.out *~
 	$(MAKE) -fMakefile.big clean
@@ -87,6 +104,4 @@ clean_subdirs: clean_vejit clean_vednn # get rid of unpacked tarballs (if any)
 		done;
 realclean: clean clean_subdirs
 	$(MAKE) -fMakefile.big realclean
-jitconv resnext-t8.log:
-	$(MAKE) -fMakefile.big $@
 #
